version: '3.1'

services:

  mongo:
    image: mongo:6.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: "exit 0"
    env_file:
      - .env.dev

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env.dev

volumes:
  mongodb:
