.env:
  directory: "/"
  filename: .env
  ignoreIfMalformed: false
  ignoreIfMissing: false
  systemProperties: false
  prefix: "env."

server:
  port: ${env.PORT:8080}

spring:
  devtools:
    livereload:
      port: 35730
  data:
    mongodb:
      database: ${env.MONGO_DATABASE:movies-db}
      uri: ${env.MONGO_URI}